<script src="../js/libs/jquery-1.11.1.min.js" type="text/javascript"></script>
<?php if($env != 'development'):?>
    <script data-main="../js/app/main" src="../js/libs/require.js" type="text/javascript"></script>
<?php else:?>
    <script src="../js/built/libs.js?<?= filemtime($_SERVER['DOCUMENT_ROOT'] . '../js/built/libs.js')?>"></script>
    <script src="../js/built/main.js?<?= filemtime($_SERVER['DOCUMENT_ROOT'] . '../js/built/main.js')?>"></script>
<?php endif?>
<script>
      if (navigator.userAgent.indexOf('Mac OS X') != -1) {
        $("body").addClass("chrome-mac-font");
       }
</script>